# Generated by Django 4.2.16 on 2024-09-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('People', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_time_fee_paid', models.BooleanField(default=False)),
                ('mathitis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='People.mathites', verbose_name='Μαθητής')),
                ('months_paid', models.ManyToManyField(blank=True, related_name='paid', to='Payments.month', verbose_name='Πληρωμένοι Μήνες')),
                ('months_unpaid', models.ManyToManyField(blank=True, related_name='unpaid', to='Payments.month', verbose_name='Απλήρωτοι Μήνες')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, verbose_name='Αριθμός Απόδειξης')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό Πληρωμής')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='Payments.payment', verbose_name='Πληρωμή')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('one_time_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('months', models.ManyToManyField(related_name='payment_plans', to='Payments.month')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Payments.paymentplan', verbose_name='Σχέδιο Πληρωμής'),
        ),
    ]
