# Generated by Django 4.2.16 on 2024-09-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, verbose_name='Academic Year'),
        ),
    ]
