# Generated by Django 4.2.16 on 2024-10-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_payment_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Αριθμός Απόδειξης'),
        ),
    ]
