# Generated by Django 5.2.8 on 2025-11-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Payments", "0003_alter_receipt_receipt_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="mathitis",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="months_unpaid",
        ),
    ]
