# Generated by Django 5.2.8 on 2025-11-19 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payments", "0004_remove_payment_mathitis_remove_payment_months_unpaid"),
        ("People", "0012_guardian_remove_mathites_kidemones_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="People.student",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="months_paid",
            field=models.ManyToManyField(
                blank=True,
                related_name="paid",
                to="Payments.month",
                verbose_name="Paid Months",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="Payments.paymentplan",
                verbose_name="Payment Plan",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount Paid"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="Payments.payment",
                verbose_name="Payment",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="receipt_number",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Receipt Number"
            ),
        ),
    ]
