# Generated by Django 4.2.16 on 2024-09-20 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxeis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('reset_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Τάξεις',
                'verbose_name_plural': 'Τάξεις',
            },
        ),
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=django.utils.timezone.now, verbose_name='Attendance Date')),
                ('attendance_records', models.JSONField(verbose_name='Attendance Records')),
                ('taxh_nai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_attendances', to='Class_related.taxeis', verbose_name='Τάξη')),
            ],
            options={
                'verbose_name': 'Attendance History',
                'verbose_name_plural': 'Attendance Histories',
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arx', models.CharField(max_length=20, verbose_name='Όνομα')),
                ('name_tel', models.CharField(max_length=20, verbose_name='Επίθετο')),
                ('attendance', models.BooleanField(default=False, verbose_name='Παρουσία')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone')),
                ('generated_field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Generated Field')),
                ('taxh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='Class_related.taxeis', verbose_name='Τάξη')),
            ],
            options={
                'verbose_name': 'Παρουσίες',
                'verbose_name_plural': 'Παρουσίες',
            },
        ),
    ]
