# Generated by Django 4.2.16 on 2024-10-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class_related', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancehistory',
            options={'ordering': ['-attendance_date'], 'verbose_name': 'Ιστορικό Παρουσιών', 'verbose_name_plural': 'Ιστορικό Παρουσιών'},
        ),
    ]
