# Generated by Django 5.2.8 on 2025-11-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Class_related", "0002_alter_attendancehistory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Name")),
                ("reset_time", models.TimeField(verbose_name="Reset Time")),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
            },
        ),
        migrations.RemoveField(
            model_name="attendancehistory",
            name="taxh_nai",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="taxh",
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
            },
        ),
        migrations.AlterModelOptions(
            name="attendancehistory",
            options={
                "ordering": ["-attendance_date"],
                "verbose_name": "Attendance History",
                "verbose_name_plural": "Attendance History",
            },
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="attendance",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="generated_field",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="name_arx",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="name_tel",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="telephone",
        ),
        migrations.AddField(
            model_name="attendance",
            name="present",
            field=models.BooleanField(default=False, verbose_name="Present"),
        ),
    ]
