# Generated by Django 5.2.8 on 2025-11-19 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Class_related", "0003_grade_remove_attendancehistory_taxh_nai_and_more"),
        ("People", "0012_guardian_remove_mathites_kidemones_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="People.student",
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Timestamp"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendances",
                to="Class_related.grade",
                verbose_name="Grade",
            ),
        ),
        migrations.AddField(
            model_name="attendancehistory",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_attendances",
                to="Class_related.grade",
                verbose_name="Grade",
            ),
        ),
        migrations.DeleteModel(
            name="Taxeis",
        ),
    ]
