# Generated by Django 5.2.8 on 2025-11-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_related', '0004_attendance_student_attendance_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='lesson_duration',
            field=models.IntegerField(default=2, verbose_name='Lesson Duration (hours)'),
        ),
    ]
