# Generated by Django 5.2.8 on 2025-11-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_related', '0005_grade_lesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='class_time',
            field=models.TimeField(blank=True, help_text='Time when the class starts', null=True, verbose_name='Class Time'),
        ),
        migrations.AddField(
            model_name='grade',
            name='weekdays',
            field=models.CharField(blank=True, help_text='Comma-separated weekdays (e.g., MONDAY,WEDNESDAY,FRIDAY)', max_length=100, verbose_name='Weekdays'),
        ),
    ]
