# Generated by Django 4.2.16 on 2024-09-20 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Class_related', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kidemones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arx', models.CharField(max_length=20, verbose_name='Όνομα')),
                ('name_tel', models.CharField(max_length=20, verbose_name='Επίθετο')),
                ('til', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '1234567890' and it must be 10 digits", regex='^\\+?1?\\d{9,15}$')], verbose_name='Τηλέφωνο')),
                ('address', models.CharField(max_length=20, verbose_name='Διεύθυνση')),
            ],
            options={
                'verbose_name': 'Κηδεμόνες',
                'verbose_name_plural': 'Κηδεμόνες',
            },
        ),
        migrations.CreateModel(
            name='Mathites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arx', models.CharField(max_length=20, verbose_name='Όνομα')),
                ('name_tel', models.CharField(max_length=20, verbose_name='Επίθετο')),
                ('active', models.BooleanField(default=True)),
                ('til', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '1234567890' and it must be 10 digits", regex='^\\+?1?\\d{9,15}$')], verbose_name='Τηλέφωνο')),
                ('address', models.CharField(max_length=20, verbose_name='Διεύθυνση')),
                ('foto', models.ImageField(blank=True, upload_to='images/', verbose_name='Φωτογραφία')),
                ('Parousies', models.IntegerField(default=0)),
                ('Aparousies', models.IntegerField(default=0)),
                ('generated_field', models.CharField(blank=True, editable=False, max_length=100)),
                ('kidemones', models.ManyToManyField(blank=True, related_name='mathites_set', to='People.kidemones', verbose_name='Κηδεμόνες')),
                ('taxh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Class_related.taxeis', verbose_name='Τάξη')),
            ],
            options={
                'verbose_name': 'Μαθητές',
                'verbose_name_plural': 'Μαθητές',
            },
        ),
        migrations.AddField(
            model_name='kidemones',
            name='mathites_relate',
            field=models.ManyToManyField(blank=True, related_name='kidemones_set', to='People.mathites', verbose_name='Μαθητές'),
        ),
    ]
