# Generated by Django 4.2.16 on 2024-09-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
        ('People', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathites',
            name='payment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payments.paymentplan', verbose_name='Σχέδιο Πληρωμής'),
        ),
    ]
