# Generated by Django 4.2.16 on 2024-09-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0002_mathites_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathites',
            name='generated_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
