# Generated by Django 4.2.16 on 2024-10-01 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0003_alter_mathites_generated_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidemones',
            name='epagelma',
            field=models.CharField(blank=True, max_length=20, verbose_name='Επάγγελμα'),
        ),
        migrations.AddField(
            model_name='kidemones',
            name='taxidr_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='Ταχυδρομικός κώδικας'),
        ),
        migrations.AddField(
            model_name='kidemones',
            name='til_stath',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '1234567890' and it must be 10 digits", regex='^\\+?1?\\d{9,15}$')], verbose_name='Σταθερό'),
        ),
        migrations.AddField(
            model_name='mathites',
            name='School',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mathites',
            name='School_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mathites',
            name='til',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '1234567890' and it must be 10 digits", regex='^\\+?1?\\d{9,15}$')], verbose_name='Τηλέφωνο'),
        ),
    ]
