# Generated by Django 4.2.16 on 2024-10-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0004_kidemones_epagelma_kidemones_taxidr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidemones',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mathites',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
