# Generated by Django 4.2.16 on 2024-10-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0005_kidemones_email_mathites_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidemones',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mathites',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
