# Generated by Django 4.2.16 on 2024-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0006_alter_kidemones_email_alter_mathites_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidemones',
            name='epagelma',
            field=models.CharField(blank=True, max_length=30, verbose_name='Επάγγελμα'),
        ),
    ]
