# Generated by Django 4.2.16 on 2024-10-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0007_alter_kidemones_epagelma'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathites',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Γέννησης'),
        ),
    ]
