# Generated by Django 4.2.16 on 2024-10-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0008_mathites_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathites',
            name='School_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
