# Generated by Django 4.2.16 on 2024-10-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Class_related', '0002_alter_attendancehistory_options'),
        ('People', '0009_alter_mathites_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathites',
            name='taxh',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Class_related.taxeis', verbose_name='Τάξη'),
        ),
    ]
