# Generated by Django 5.2.8 on 2025-11-19 22:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Class_related", "0003_grade_remove_attendancehistory_taxh_nai_and_more"),
        ("Payments", "0004_remove_payment_mathitis_remove_payment_months_unpaid"),
        ("People", "0011_alter_mathites_taxh"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=20, verbose_name="Last Name"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '1234567890' and must be 10 digits.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                ("address", models.CharField(max_length=20, verbose_name="Address")),
                (
                    "landline_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '1234567890' and must be 10 digits.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Landline Number",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Postal Code"
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Profession"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=30, verbose_name="Email"),
                ),
            ],
            options={
                "verbose_name": "Guardian",
                "verbose_name_plural": "Guardians",
            },
        ),
        migrations.RemoveField(
            model_name="mathites",
            name="kidemones",
        ),
        migrations.RemoveField(
            model_name="mathites",
            name="payment_plan",
        ),
        migrations.RemoveField(
            model_name="mathites",
            name="taxh",
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=20, verbose_name="Last Name"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '1234567890' and must be 10 digits.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                ("address", models.CharField(max_length=20, verbose_name="Address")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="images/", verbose_name="Photo"
                    ),
                ),
                (
                    "school",
                    models.CharField(blank=True, max_length=20, verbose_name="School"),
                ),
                (
                    "school_year",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="School Year"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Birth Date"),
                ),
                ("presences", models.IntegerField(default=0, verbose_name="Presences")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=30, verbose_name="Email"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Class_related.grade",
                        verbose_name="Grade",
                    ),
                ),
                (
                    "guardians",
                    models.ManyToManyField(
                        blank=True,
                        related_name="students",
                        to="People.guardian",
                        verbose_name="Guardians",
                    ),
                ),
                (
                    "payment_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Payments.paymentplan",
                        verbose_name="Payment Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.DeleteModel(
            name="Kidemones",
        ),
        migrations.DeleteModel(
            name="Mathites",
        ),
    ]
