# Generated by Django 5.2.8 on 2025-11-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0012_guardian_remove_mathites_kidemones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='absences',
            field=models.IntegerField(default=0, verbose_name='Absences'),
        ),
    ]
